# Generated by cpp4r: do not edit by hand

#' @title Compute mean on a background thread (print result)
#' @param data numeric vector
#' @description Launches a background thread that computes the mean of \code{data}.
#'   The result is printed via \code{Rprintf} once the background thread finishes.
#'   This matches the example from the "Using later from C++" vignette.
#' @export
#' @examples
#' asyncMean(c(1, 2, 3))
#' later::run_now(2)
asyncMean <- function(data) {
	invisible(.Call(`_laterexample_asyncMean`, data))
}

#' @title Compute mean on a background thread (callback result)
#' @param data numeric vector
#' @param callback an R function that will be called with the mean as its argument
#' @description Like \code{asyncMean} but delivers the result to an R callback
#'   instead of printing it. Useful for testing and for integrating with promises.
#' @export
#' @examples
#' result <- NULL
#' asyncMeanCb(c(1, 2, 3), function(x) result <<- x)
#' later::run_now(2)
#' result
asyncMeanCb <- function(data, callback) {
	invisible(.Call(`_laterexample_asyncMeanCb`, data, callback))
}
