// Generated by cpp4r: do not edit by hand
// clang-format off


#include "cpp4r/declarations.hpp"
#include <R_ext/Visibility.h>

// async_mean.h
void asyncMean(cpp4r::doubles data);
extern "C" SEXP _laterexample_asyncMean(SEXP data) {
  BEGIN_CPP4R
    asyncMean(cpp4r::as_cpp<cpp4r::decay_t<cpp4r::doubles>>(data));
    return R_NilValue;
  END_CPP4R
}
// async_mean.h
void asyncMeanCb(cpp4r::doubles data, SEXP callback);
extern "C" SEXP _laterexample_asyncMeanCb(SEXP data, SEXP callback) {
  BEGIN_CPP4R
    asyncMeanCb(cpp4r::as_cpp<cpp4r::decay_t<cpp4r::doubles>>(data), cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(callback));
    return R_NilValue;
  END_CPP4R
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_laterexample_asyncMean",   (DL_FUNC) &_laterexample_asyncMean,   1},
    {"_laterexample_asyncMeanCb", (DL_FUNC) &_laterexample_asyncMeanCb, 2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_laterexample(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
